development:
  adapter: postgresql
  host: localhost
  encoding: unicode
  database: slovenstina_development

test:
  adapter: postgresql
  host: localhost
  encoding: unicode
  database: slovenstina_test

production:
  adapter: postgresql
  host: localhost
  encoding: unicode
  database: slovenstina_development
